
export const HEADER_TITLES = [
  { path: "/sales/invoices/new", title: "Nueva factura de venta" },
  { path: "/sales/invoices", title: "Facturas de venta" },
  { path: "/sales/customers", title: "Clientes" },
  { path: "/sales/customers/*", title: "Detalles del cliente" },
  { path: "/purchases/purchase-requests", title: "Solicitudes de compra" },
  { path: "/purchases/purchase-requests/new", title: "Nueva solicitud de compra" },
  { path: "/purchases/purchase-requests/*", title: "Detalles de la solicitud de compra" },
  { path: "/purchases/quotation-request/new/*", title: "Nueva solicitud de cotización" },
  { path: "/purchases/purchase-orders", title: "Órdenes de compra" },
  { path: "/purchases/purchase-orders/new", title: "Nueva orden de compra" },
  { path: "/purchases/purchase-orders/*", title: "Detalles de la orden de compra" },
  { path: "/purchases/purchase-receipts", title: "Recibos de compra" },
  { path: "/purchases/purchase-receipts/new", title: "Nuevo recibo de compra" },
  { path: "/purchases/vendors", title: "Proveedores" },
  { path: "/purchases/vendors/*", title: "Detalles del proveedor" },
  { path: "/purchases/vendors/new", title: "Nuevo proveedor" },
  { path: "/purchases/bills", title: "Facturas de compra" },
  { path: "/purchases/bills/new", title: "Cargar factura de compra" },
  { path: "/banking/payments/new", title: "Registrar pago" },
];
