import { createApi, fetchBaseQuery } from '@reduxjs/toolkit/query/react';

export const erpApi = createApi({
  reducerPath: 'erpApi',
  baseQuery: fetchBaseQuery({ baseUrl: '/erp/api/' }),
  endpoints: () => ({}),
  tagTypes: [
    'Supplier',
    'PurchaseOrder',
    'Bill',
    'Invoice',
    'Customer',
    'DeliveryNote',
    'CreditNote',
    'DebitNote',
    'PurchaseRequest',
    'PurchaseReceipt',
    'Currency',
    'PaymentTerm',
    'PaymentMethod',
    'Tax',
    'AccountingAccount',
    'JournalEntry',
    'AccountsPayable',
    'AccountsReceivable',
    'CostCenter',
    'Payment',
    'Receipt',
    'Journal',
    'Service',
    'Material',
    'JobPosition',
    'Procedure',
    'MedicalExam',
    'Attribute',
    'InternalTransfer',
    'ProductTemplate',
    'Product',
    'Warehouse',
    'Location',
    'Charge',
    'EconomicActivity',
  ],
});
